"""
Seed a complete, realistic DEMO account for the defense walkthrough.

Creates ONE login-able user whose data looks exactly like a real runner's,
because every step goes through the SAME code paths as production usage:

  - GPS runs (encoded polyline + per-km laps + HR-zone seconds) so the
    activity map, splits table and HR donut all render like a real upload.
  - An active training plan generated by the real ``generate_plan`` that
    STARTED in the past, so its past weeks show a genuine completed/skipped
    grid. Runs are created on the plan's past workout days and linked +
    scored through the real ``score_workout_performance`` (L2).
  - A few workouts are skipped (→ shown as missed); the week immediately
    before "today" is deliberately under-done so the L3 missed-week recovery
    rewrite + banner appears on the current week.
  - CTL/ATL/TSB history and current VDOT via the real
    ``recalculate_user_metrics`` pipeline.
  - A finish-time prediction for the target marathon (hybrid predictor).

Usage:
  python manage.py seed_demo
  python manage.py seed_demo --email=demo@enduranceai.app --password=EnduranceDemo2026 \
      --target=berlin --past-weeks=10 --future-weeks=6 --days-per-week=4
"""
import math
import random
from datetime import date, datetime, timedelta, timezone

from django.core.management.base import BaseCommand, CommandError
from django.contrib.auth import get_user_model
from django.db import transaction

from apps.activities.models import Activity
from apps.activities.parsers.base import encode_polyline, detect_hr_zones
from apps.activities.tasks import recalculate_user_metrics
from apps.races.models import Marathon, Prediction
from apps.plans.models import TrainingPlan, PlanWeek, PlanWorkout
from apps.plans.generator import generate_plan, score_workout_performance

User = get_user_model()

# Routes are drawn around Ufa (home city of the university) for local flavour.
UFA_CENTER = (54.7388, 55.9721)


class Command(BaseCommand):
    help = 'Seed a full realistic demo account (user + GPS runs + plan + prediction)'

    def add_arguments(self, parser):
        parser.add_argument('--email', default='demo@enduranceai.app')
        parser.add_argument('--password', default='EnduranceDemo2026')
        parser.add_argument('--first-name', default='Демо')
        parser.add_argument('--last-name', default='Бегунов')
        parser.add_argument('--target', default='berlin',
                            help='Marathon name fragment to set as target race')
        parser.add_argument('--past-weeks', type=int, default=10,
                            help='How many weeks the plan has already been running')
        parser.add_argument('--future-weeks', type=int, default=6,
                            help='Weeks from today until race day (>= 2)')
        parser.add_argument('--days-per-week', type=int, default=4)
        parser.add_argument('--start-vdot', type=float, default=46.0)
        parser.add_argument('--seed', type=int, default=42)

    @transaction.atomic
    def handle(self, *args, **opts):
        email = opts['email']
        past_weeks = opts['past_weeks']
        future_weeks = max(2, opts['future_weeks'])
        days_per_week = opts['days_per_week']
        rng = random.Random(opts['seed'])

        # ── 1. User (create or reset) ───────────────────────────────────
        user, created = User.objects.get_or_create(email=email)
        user.first_name = opts['first_name']
        user.last_name = opts['last_name']
        user.sex = 'M'
        user.date_of_birth = date(1994, 5, 14)          # ~31 yo
        user.max_hr = 190
        user.units = 'metric'
        user.lang = 'ru'
        user.onboarding_completed = True
        user.is_active = True
        user.set_password(opts['password'])
        user.current_vdot = round(opts['start_vdot'], 2)   # seed so generate_plan has paces
        user.save()

        # Idempotent reset of this user's generated data
        Activity.objects.filter(user=user).delete()
        Prediction.objects.filter(user=user).delete()
        TrainingPlan.objects.filter(user=user).delete()
        self.stdout.write(f'User {"created" if created else "reset"}: {email}')

        # ── 2. Timeline + target race ───────────────────────────────────
        today = date.today()
        this_monday = today - timedelta(days=today.weekday())
        plan_start = this_monday - timedelta(weeks=past_weeks)
        race_date = today + timedelta(weeks=future_weeks)

        marathon = Marathon.objects.filter(name__icontains=opts['target']).first()
        if not marathon:
            raise CommandError(
                f'No marathon matching {opts["target"]!r}. '
                f'Run: python manage.py import_marathons'
            )
        user.target_marathon = marathon
        user.target_race_date = race_date
        user.save(update_fields=['target_marathon', 'target_race_date'])

        # ── 3. Generate the plan (past → future) via the real generator ──
        weeks_data = generate_plan(
            user, race_date,
            days_per_week=days_per_week,
            cutback_enabled=True,
            start_date=plan_start,
        )
        plan = TrainingPlan.objects.create(
            user=user,
            start_date=plan_start,
            race_date=race_date,
            vdot_at_creation=user.current_vdot,
            days_per_week=days_per_week,
            status='active',
        )
        for wdata in weeks_data:
            week = PlanWeek.objects.create(
                plan=plan, week_number=wdata['week_number'],
                phase=wdata['phase'], total_km=wdata['total_km'],
            )
            for wo in wdata['workouts']:
                PlanWorkout.objects.create(
                    plan_week=week,
                    day_of_week=wo['day_of_week'],
                    workout_type=wo['workout_type'],
                    distance_km=wo.get('distance_km'),
                    pace_min_sec=wo.get('pace_min_sec'),
                    pace_max_sec=wo.get('pace_max_sec'),
                    structure=wo.get('structure', {}),
                )

        # The plan is back-dated: its workouts live in the past, but created_at
        # defaults to now(). The UI treats any not-completed workout dated
        # BEFORE created_at as "pre-plan" (neutral «ДО ПЛАНА» badge) and never
        # as missed — so without this the whole past reads as pre-plan and the
        # completed/missed grid disappears. Pin created_at to the plan start.
        TrainingPlan.objects.filter(pk=plan.pk).update(
            created_at=datetime(plan_start.year, plan_start.month, plan_start.day,
                                tzinfo=timezone.utc),
        )

        current_week_num = (today - plan_start).days // 7 + 1
        prev_week_num = current_week_num - 1     # deliberately under-do this one

        # ── 4. Create GPS runs on past workout days + link/score them ────
        completed = skipped = 0
        workouts = (PlanWorkout.objects
                    .filter(plan_week__plan=plan)
                    .exclude(workout_type='rest')
                    .select_related('plan_week')
                    .order_by('plan_week__week_number', 'day_of_week'))

        for wo in workouts:
            wnum = wo.plan_week.week_number
            target = plan_start + timedelta(days=(wnum - 1) * 7 + (wo.day_of_week or 0))
            if target > today:
                continue   # future workout — leave it planned

            # Skip policy: the week right before "today" is fully missed (a
            # plausible "sick week"), which pushes the previous-week miss ratio
            # over 50% and makes the L3 recovery rewrite + banner appear on the
            # current week. Elsewhere a light random skip keeps the grid honest.
            force_miss = (wnum == prev_week_num)
            if force_miss or rng.random() < 0.12:
                skipped += 1
                continue

            act = self._make_run(user, wo, target, rng)
            wo.completed = True
            wo.activity = act
            wo.actual_pace_sec = (
                int(round(float(act.avg_pace_sec_per_km)))
                if act.avg_pace_sec_per_km else None
            )
            wo.performance_score = score_workout_performance(
                wo.actual_pace_sec, wo.pace_min_sec, wo.pace_max_sec, wo.workout_type,
            )
            wo.save(update_fields=[
                'completed', 'activity', 'actual_pace_sec', 'performance_score',
            ])
            completed += 1

        self.stdout.write(self.style.SUCCESS(
            f'Runs: {completed} completed, {skipped} skipped '
            f'(plan {len(weeks_data)} weeks, now in week {current_week_num})'
        ))

        # ── 5. Real metric pipeline (VDOT, CTL/ATL/TSB, L1/L3 adaptation) ─
        self.stdout.write('Recalculating VDOT / CTL / ATL / TSB ...')
        recalculate_user_metrics(str(user.id))

        # ── 6. Finish-time prediction for the dashboard ─────────────────
        user.refresh_from_db()
        if user.current_vdot:
            self._make_prediction(user, marathon, race_date)
        else:
            self.stdout.write(self.style.WARNING('No VDOT computed — skipped prediction'))

        # ── 7. Summary ──────────────────────────────────────────────────
        user.refresh_from_db()
        self.stdout.write(self.style.SUCCESS(
            '\n✅ Demo account ready\n'
            f'  Login:   {email} / {opts["password"]}\n'
            f'  VDOT:    {user.current_vdot}\n'
            f'  CTL/ATL/TSB: {user.current_ctl} / {user.current_atl} / {user.current_tsb}\n'
            f'  Target:  {marathon.name} on {race_date.isoformat()}\n'
            f'  Plan:    week {current_week_num}/{len(weeks_data)} '
            f'(prev week under-done → L3 recovery should show)\n'
        ))

    # ────────────────────────────────────────────────────────────────────
    def _make_run(self, user, wo, run_date, rng) -> Activity:
        """Create one realistic GPS Activity matching a planned workout."""
        planned_dist = float(wo.distance_km or 8.0)
        dist_km = round(planned_dist * rng.uniform(0.97, 1.05), 2)

        # Pace relative to the planned window, tuned per workout type so the
        # L2 performance score lands in a believable spread (mostly "in zone").
        p_min = wo.pace_min_sec or 330
        p_max = wo.pace_max_sec or int(p_min * 1.1)
        wt = wo.workout_type
        if wt in ('easy', 'long'):
            pace = (p_min * 0.95 if rng.random() < 0.15           # occasionally too fast (-1)
                    else rng.uniform(p_min, p_max))
        elif wt in ('tempo', 'marathon_pace'):
            pace = p_min * (1.04 if rng.random() < 0.18 else rng.uniform(0.99, 1.02))
        else:  # interval / repetition — beating target is good
            pace = p_min * rng.uniform(0.97, 1.015)
        pace = round(pace, 1)
        duration = int(dist_km * pace)

        # HR profile by workout type
        hr_target = {
            'easy': 138, 'long': 148, 'tempo': 168,
            'marathon_pace': 158, 'interval': 176, 'repetition': 180,
        }.get(wt, 145) + rng.randint(-3, 3)

        track = _synth_track(dist_km, duration, hr_target, user.max_hr or 190,
                             UFA_CENTER, rng)

        start_dt = datetime(
            run_date.year, run_date.month, run_date.day,
            rng.choice([7, 8, 18, 19]), rng.randint(0, 59), tzinfo=timezone.utc,
        )
        return Activity.objects.create(
            user=user,
            start_time=start_dt,
            distance_km=dist_km,
            duration_sec=duration,
            avg_pace_sec_per_km=round(duration / dist_km, 2),
            avg_hr=track['avg_hr'],
            max_hr=track['max_hr'],
            elevation_gain_m=track['elevation_gain_m'],
            elevation_loss_m=track['elevation_loss_m'],
            avg_cadence=track['avg_cadence'],
            calories=track['calories'],
            laps=track['laps'],
            hr_zones_sec=track['hr_zones_sec'],
            polyline=track['polyline'],
            source='gpx',
            is_valid=True,
        )

    def _make_prediction(self, user, marathon, race_date):
        from ml.src.predict import predict_finish_time
        temp_c = (marathon.get_avg_temp(race_date.month) or 15.0
                  if marathon.avg_temp_by_month else 15.0)
        humidity_pct, wind_ms = 65.0, 1.0
        r = predict_finish_time(user, marathon, race_date, temp_c, humidity_pct, wind_ms)
        Prediction.objects.create(
            user=user, marathon=marathon,
            target_distance_km=marathon.distance_km, race_date=race_date,
            base_time_sec=r['base_time_sec'],
            course_difficulty_coefficient=r['course_difficulty_coefficient'],
            weather_index=r['weather_index'],
            predicted_time_sec=r['predicted_time_sec'],
            confidence_interval_sec=r['confidence_interval_sec'],
            feature_importance=r.get('feature_importance', []),
            model_version='hybrid_v1',
            features_snapshot={'vdot': float(user.current_vdot), 'temp_c': temp_c,
                               'mode': r['mode'], 'seeded': True},
        )
        self.stdout.write(self.style.SUCCESS(
            f'Prediction: {r["predicted_time_formatted"]} '
            f'(±{r["confidence_interval_sec"] // 60} min, {r["mode"]})'
        ))


# ════════════════════════════════════════════════════════════════════════
def _synth_track(distance_km, duration_sec, hr_target, max_hr, center, rng):
    """Build a believable GPS track: polyline + km laps + HR-zone seconds."""
    # Per-second HR series (warmup ramp + slight cardiac drift + noise)
    hr_series = []
    for s in range(max(1, duration_sec)):
        ramp = min(1.0, s / 120.0)
        drift = hr_target * 0.03 * (s / duration_sec) if duration_sec else 0
        hr = hr_target * (0.84 + 0.16 * ramp) + drift + rng.gauss(0, 2.5)
        hr_series.append(int(min(max_hr, max(95, hr))))
    avg_hr = int(sum(hr_series) / len(hr_series))
    max_hr_actual = max(hr_series)

    # Wandering GPS route of roughly the right length (~1 point / 100 m)
    n = max(8, int(distance_km * 10))
    step_m = distance_km * 1000 / (n - 1)
    lat, lon = center[0] + rng.uniform(-0.02, 0.02), center[1] + rng.uniform(-0.02, 0.02)
    heading = rng.uniform(0, 2 * math.pi)
    pts = [(round(lat, 5), round(lon, 5))]
    elev = rng.uniform(100, 160)
    elevations = [elev]
    for _ in range(1, n):
        heading += rng.gauss(0, 0.35)
        lat += (step_m * math.sin(heading)) / 111320.0
        lon += (step_m * math.cos(heading)) / (111320.0 * math.cos(math.radians(lat)))
        elev += rng.gauss(0, 1.4)
        pts.append((round(lat, 5), round(lon, 5)))
        elevations.append(elev)

    gain = sum(max(0, elevations[i] - elevations[i - 1]) for i in range(1, len(elevations)))
    loss = sum(max(0, elevations[i - 1] - elevations[i]) for i in range(1, len(elevations)))

    # Per-km laps with avg pace/HR/elevation sliced from the second-by-second HR
    laps = []
    pace = duration_sec / distance_km if distance_km else 0
    full_km = int(distance_km)
    t_cursor = 0
    for km in range(1, full_km + 1):
        lap_sec = int(pace * rng.uniform(0.97, 1.03))
        seg = hr_series[t_cursor:t_cursor + lap_sec] or [avg_hr]
        t_cursor += lap_sec
        laps.append({
            'lap': km,
            'distance_km': 1.0,
            'duration_sec': lap_sec,
            'avg_pace_sec_per_km': round(lap_sec, 1),
            'avg_hr': int(sum(seg) / len(seg)),
            'elevation_gain_m': round(gain / max(1, full_km), 1),
            'elevation_loss_m': round(loss / max(1, full_km), 1),
            'avg_elevation_m': round(sum(elevations) / len(elevations), 1),
        })
    frac = round(distance_km - full_km, 2)
    if frac >= 0.05:
        lap_sec = int(pace * frac)
        seg = hr_series[t_cursor:] or [avg_hr]
        laps.append({
            'lap': full_km + 1, 'distance_km': frac, 'duration_sec': lap_sec,
            'avg_pace_sec_per_km': round(pace, 1),
            'avg_hr': int(sum(seg) / len(seg)),
            'elevation_gain_m': round(gain / max(1, full_km), 1),
            'elevation_loss_m': round(loss / max(1, full_km), 1),
            'avg_elevation_m': round(sum(elevations) / len(elevations), 1),
        })

    return {
        'polyline': encode_polyline(pts),
        'laps': laps,
        'hr_zones_sec': detect_hr_zones(hr_series, max_hr),
        'avg_hr': avg_hr,
        'max_hr': max_hr_actual,
        'elevation_gain_m': round(gain, 1),
        'elevation_loss_m': round(loss, 1),
        'avg_cadence': rng.randint(166, 178),
        'calories': int(distance_km * 65),
    }
