# Generated by Django 4.2.13 on 2026-05-19 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ctl', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('atl', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tsb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vdot_rolling', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hr_efficiency', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'daily_metrics',
                'ordering': ['-date'],
            },
        ),
    ]
