# Generated by Django 4.2.13 on 2026-05-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailymetrics',
            index=models.Index(fields=['user', '-date'], name='daily_metri_user_id_882aef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymetrics',
            unique_together={('user', 'date')},
        ),
    ]
