# Generated by Django 4.2.13 on 2026-05-19 22:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('max_hr', models.SmallIntegerField(blank=True, help_text='Max heart rate bpm', null=True)),
                ('target_race_date', models.DateField(blank=True, null=True)),
                ('target_finish_sec', models.IntegerField(blank=True, null=True)),
                ('units', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=10)),
                ('lang', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_vdot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_ctl', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current_atl', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current_tsb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('training_weeks', models.SmallIntegerField(default=0, help_text='Weeks with training data')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('target_marathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_users', to='races.marathon')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
            },
        ),
    ]
