# Generated by Django 4.2.13 on 2026-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='analytics_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
