# Generated by Django 4.2.13 on 2026-05-19 22:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('distance_km', models.DecimalField(decimal_places=3, default=42.195, max_digits=6)),
                ('elevation_gain_m', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('elevation_loss_m', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('difficulty_coefficient', models.DecimalField(decimal_places=4, default=1.0, max_digits=6)),
                ('gpx_file_path', models.CharField(blank=True, max_length=500)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('avg_temp_by_month', models.JSONField(blank=True, default=dict)),
                ('official_url', models.CharField(blank=True, max_length=500)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marathons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarathonResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField()),
                ('age_group', models.CharField(blank=True, max_length=10)),
                ('sex', models.CharField(blank=True, max_length=1)),
                ('finish_time_sec', models.IntegerField()),
                ('position_overall', models.IntegerField(blank=True, null=True)),
                ('position_age_group', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'db_table': 'marathon_results',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('race_date', models.DateField(blank=True, null=True)),
                ('base_time_sec', models.IntegerField(blank=True, null=True)),
                ('course_difficulty_coefficient', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('weather_index', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('predicted_time_sec', models.IntegerField()),
                ('confidence_interval_sec', models.IntegerField(blank=True, null=True)),
                ('race_readiness_score', models.SmallIntegerField(blank=True, null=True)),
                ('features_snapshot', models.JSONField(blank=True, default=dict)),
                ('feature_importance', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(blank=True, max_length=20)),
                ('marathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='races.marathon')),
            ],
            options={
                'db_table': 'predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
