# Generated by Django 4.2.13 on 2026-05-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marathonresult',
            name='marathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.marathon'),
        ),
        migrations.AddIndex(
            model_name='marathonresult',
            index=models.Index(fields=['marathon', 'year', 'finish_time_sec'], name='marathon_re_maratho_8c38af_idx'),
        ),
    ]
