# Generated by Django 4.2.13 on 2026-05-21 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_marathons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marathon',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marathon',
            name='major',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marathon',
            name='polyline',
            field=models.TextField(blank=True),
        ),
    ]
