# Generated by Django 4.2.13 on 2026-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_marathon_major_custom_polyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='elevation_profile',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
