# Generated by Django 4.2.13 on 2026-06-03 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0004_activity_external_strava_id_alter_activity_source'),
        ('races', '0004_marathon_elevation_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('race_date', models.DateField()),
                ('actual_time_sec', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending — target race in the future'), ('completed', 'Completed — finished the race'), ('dnf', 'Did Not Finish'), ('cancelled', 'Cancelled — did not start')], default='pending', max_length=20)),
                ('vdot_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ctl_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('atl_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tsb_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('course_coefficient_used', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('weather_snapshot', models.JSONField(blank=True, default=dict)),
                ('plan_compliance_pct', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_attempts', to='activities.activity')),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='races.marathon')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_attempts', to='races.prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marathon_attempts',
                'ordering': ['-race_date'],
                'indexes': [models.Index(fields=['user', '-race_date'], name='marathon_at_user_id_6c7386_idx'), models.Index(fields=['marathon', '-race_date'], name='marathon_at_maratho_45bcfc_idx'), models.Index(fields=['status'], name='marathon_at_status_ef3287_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='marathonattempt',
            constraint=models.UniqueConstraint(fields=('user', 'marathon', 'race_date'), name='unique_user_marathon_race_date'),
        ),
    ]
