# Generated by Django 4.2.13 on 2026-06-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_marathonattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathonattempt',
            name='training_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
