# Generated by Django 4.2.13 on 2026-05-19 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.SmallIntegerField()),
                ('phase', models.CharField(blank=True, choices=[('base', 'Base'), ('early_quality', 'Early Quality'), ('late_quality', 'Late Quality'), ('taper', 'Taper')], max_length=20)),
                ('total_km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'plan_weeks',
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='PlanWorkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField(blank=True, null=True)),
                ('workout_type', models.CharField(choices=[('easy', 'Easy'), ('tempo', 'Tempo'), ('interval', 'Interval'), ('repetition', 'Repetition'), ('long', 'Long Run'), ('marathon_pace', 'Marathon Pace'), ('rest', 'Rest')], default='easy', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('structure', models.JSONField(blank=True, default=dict)),
                ('pace_min_sec', models.IntegerField(blank=True, null=True)),
                ('pace_max_sec', models.IntegerField(blank=True, null=True)),
                ('hr_min', models.SmallIntegerField(blank=True, null=True)),
                ('hr_max', models.SmallIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'plan_workouts',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('race_date', models.DateField()),
                ('target_time_sec', models.IntegerField(blank=True, null=True)),
                ('vdot_at_creation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_per_week', models.SmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
