# Generated by Django 4.2.13 on 2026-05-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='races.prediction'),
        ),
    ]
