# Generated by Django 4.2.13 on 2026-05-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('plans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planworkout',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='planworkout',
            name='plan_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='plans.planweek'),
        ),
        migrations.AddField(
            model_name='planweek',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='plans.trainingplan'),
        ),
        migrations.AlterUniqueTogether(
            name='planweek',
            unique_together={('plan', 'week_number')},
        ),
    ]
