# Generated by Django 4.2.13 on 2026-05-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='last_paces_refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='vdot_at_last_refresh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
