# Generated by Django 4.2.13 on 2026-05-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_trainingplan_last_paces_refresh_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planworkout',
            name='actual_pace_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planworkout',
            name='performance_score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='last_recovery_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='last_recovery_week_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
