# Generated by Django 4.2.13 on 2026-06-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_planworkout_actual_pace_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planworkout',
            name='shift_days',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
