# Generated by Django 4.2.13 on 2026-05-21 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('athlete_id', models.BigIntegerField()),
                ('athlete_username', models.CharField(blank=True, max_length=255)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('total_imported', models.IntegerField(default=0)),
                ('is_broken', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strava_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'strava_connections',
            },
        ),
    ]
