# Generated by Django 4.2.13 on 2026-05-19 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('start_time', models.DateTimeField()),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('duration_sec', models.IntegerField()),
                ('avg_pace_sec_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_hr', models.SmallIntegerField(blank=True, null=True)),
                ('max_hr', models.SmallIntegerField(blank=True, null=True)),
                ('elevation_gain_m', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('elevation_loss_m', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('avg_cadence', models.SmallIntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('vdot_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tss', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('laps', models.JSONField(blank=True, default=list)),
                ('hr_zones_sec', models.JSONField(blank=True, default=dict)),
                ('polyline', models.TextField(blank=True)),
                ('raw_file_path', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('fit', 'FIT'), ('gpx', 'GPX'), ('tcx', 'TCX'), ('manual', 'Manual')], default='fit', max_length=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-start_time'],
            },
        ),
    ]
