# Generated by Django 4.2.13 on 2026-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash__isnull', False)), fields=('user', 'file_hash'), name='unique_user_file_hash'),
        ),
    ]
