# Generated by Django 4.2.13 on 2026-05-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_unique_user_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='external_strava_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=models.CharField(choices=[('fit', 'FIT'), ('gpx', 'GPX'), ('tcx', 'TCX'), ('manual', 'Manual'), ('strava', 'Strava')], default='fit', max_length=10),
        ),
    ]
