# Generated by Django 4.2.13 on 2026-05-22 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('cookies', 'Cookie Policy')], max_length=20)),
                ('version', models.CharField(help_text='Semver string e.g. 1.0.0', max_length=20)),
                ('effective_date', models.DateField()),
                ('content_en', models.TextField()),
                ('content_ru', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only ONE active version per type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'policy_versions',
                'ordering': ['-effective_date'],
                'unique_together': {('policy_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legal.policyversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_acceptances',
                'indexes': [models.Index(fields=['user', 'policy'], name='policy_acce_user_id_454eeb_idx')],
            },
        ),
    ]
